# Generated by Django 4.1.3 on 2022-11-15 16:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campus_name', models.CharField(blank=True, default='', max_length=60)),
                ('State', models.IntegerField(blank=True, default='', max_length=2)),
                ('Campus_ID', models.CharField(blank=True, default='', max_length=60, null=None)),
            ],
            options={
                'verbose_name_plural': 'University Campus',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
